# Generated by Django 4.2.16 on 2024-11-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0002_user_profile_delete_users_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='firstname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
