# Generated by Django 4.2.16 on 2024-11-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagment', '0003_user_profile_firstname_user_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
