# Generated by Django 4.2.16 on 2024-11-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
