# Generated by Django 4.2.16 on 2024-11-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_joined_date_chat_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
