# Generated by Django 4.2.16 on 2024-11-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_user_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
