# Generated by Django 4.2.16 on 2024-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_chat_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
